import { NextResponse } from "next/server";
import prisma from "@/src/lib/prisma";
import { cookies } from "next/headers";
import { jwtVerify } from "jose";

export async function POST(request) {
  try {
    // 1. Ambil token dari cookies untuk verifikasi User yang sedang login
    const cookieStore = await cookies();
    const token = cookieStore.get("authToken")?.value;

    if (!token) {
      return NextResponse.json(
        { success: false, message: "Sesi tidak valid, silakan login ulang." },
        { status: 401 },
      );
    }

    // 2. Decode token untuk mendapatkan payload user id
    const secret = new TextEncoder().encode(process.env.JWT_ACCESS_KEY);
    const { payload } = await jwtVerify(token, secret);
    const userIdFromToken = payload.id;

    const now = new Date();
    const currentMonth = now.getMonth() + 1;
    const currentYear = now.getFullYear();

    // 3. Tentukan rentang waktu bulan berjalan
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endOfMonth = new Date(
      now.getFullYear(),
      now.getMonth() + 1,
      0,
      23,
      59,
      59,
    );

    // 4. Jalankan Prisma Transaction agar data aman
    const result = await prisma.$transaction(async (tx) => {
      // A. Cek ulang apakah sudah pernah EOM periode ini
      const existingLog = await tx.eomLog.findUnique({
        where: {
          period_month_period_year: {
            period_month: currentMonth,
            period_year: currentYear,
          },
        },
      });

      if (existingLog) {
        throw new Error(
          `Proses EOM untuk periode ${currentMonth}/${currentYear} sudah pernah dilakukan.`,
        );
      }

      // B. Cari Target Rekening yang ACTIVE, tidak didelete, dan tidak ada transaksi sukses/refund
      const targets = await tx.loanAccount.findMany({
        where: {
          status: "ACTIVE",
          deleted_at: null,
          current_debt_principal: { gt: 0 },
          period_start: {
            lte: endOfMonth,
          },
          transactions: {
            none: {
              paid_date: { gte: startOfMonth, lte: endOfMonth },
              payment_status: { in: ["SUCCESS", "REFUNDED"] },
              deleted_at: null,
            },
          },
        },
      });

      if (targets.length === 0) {
        throw new Error("Tidak ada rekening yang perlu diproses bulan ini.");
      }

      let totalInterestAccrued = 0;

      // C. Looping Update untuk setiap rekening target
      for (const loan of targets) {
        const interestToCharge = Number(loan.rate_amount);
        totalInterestAccrued += interestToCharge;

        // Update Saldo Hutang Bunga di LoanAccount
        await tx.loanAccount.update({
          where: { id: loan.id },
          data: {
            current_debt_interest: {
              increment: interestToCharge,
            },
          },
        });

        // Catat ke CapitalLedger menggunakan userIdFromToken
        await tx.capitalLedger.create({
          data: {
            created_by_id: userIdFromToken,
            loan_account_id: loan.id,
            amount: interestToCharge,
            type: "INTEREST_ACCRUAL",
            description: `Bunga Akrual Otomatis (EOM) - ${now.toLocaleString("id-ID", { month: "long" })} ${currentYear}`,
            notes: `Auto-generated by system for account ${loan.no_rekening}`,
          },
        });
      }

      // D. Buat Log EOM
      return await tx.eomLog.create({
        data: {
          period_month: currentMonth,
          period_year: currentYear,
          executed_by_id: userIdFromToken,
          total_accounts: targets.length,
          total_amount: totalInterestAccrued,
        },
      });
    });

    return NextResponse.json(
      {
        success: true,
        message: "Tutup buku berhasil diproses.",
        data: result, // Ini adalah object log
      },
      { status: 200 },
    );
  } catch (error) {
    console.error("POST_EOM_EXECUTE_ERROR:", error);

    // Penanganan error spesifik
    if (error.code === "P2003") {
      return NextResponse.json(
        {
          success: false,
          message: "Gagal menyimpan ledger: Relasi User tidak valid.",
        },
        { status: 400 },
      );
    }

    return NextResponse.json(
      { success: false, message: error.message || "Terjadi kesalahan server." },
      { status: 500 },
    );
  }
}
